name: "Terraform-Apply-and-Plan"

on:
  push:
    branches:
      - terraform 

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ID }}
      AWS_REGION: 'us-east-1'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan -no-color
        continue-on-error: true
      
      - name: Save Terraform Plan
        if: success()
        run: echo "${{ steps.tf-plan.outputs.stdout }}" > tfplan

      - name: Terraform Apply
        if: success()
        run: terraform apply -auto-approve tfplan